//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Common.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string LabelBytes {
            get {
                return ResourceManager.GetString("LabelBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string LabelGigabytes {
            get {
                return ResourceManager.GetString("LabelGigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string LabelKilobytes {
            get {
                return ResourceManager.GetString("LabelKilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string LabelMegabytes {
            get {
                return ResourceManager.GetString("LabelMegabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        public static string LabelPetabytes {
            get {
                return ResourceManager.GetString("LabelPetabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string LabelTerabytes {
            get {
                return ResourceManager.GetString("LabelTerabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string LocalServerName {
            get {
                return ResourceManager.GetString("LocalServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Activity Monitor service is currently unavailable.
        /// </summary>
        public static string MessageActivityMonitorServiceUnavailable {
            get {
                return ResourceManager.GetString("MessageActivityMonitorServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send series. If this problem persists, please contact your system administrator..
        /// </summary>
        public static string MessageFailedToSendSeries {
            get {
                return ResourceManager.GetString("MessageFailedToSendSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send images. If this problem persists, please contact your system administrator..
        /// </summary>
        public static string MessageFailedToSendSops {
            get {
                return ResourceManager.GetString("MessageFailedToSendSops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send study. If this problem persists, please contact your system administrator..
        /// </summary>
        public static string MessageFailedToSendStudy {
            get {
                return ResourceManager.GetString("MessageFailedToSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start reindex operation, possibly because a conflicting operation is currently running.  If this problem persists, please contact your system administrator..
        /// </summary>
        public static string MessageFailedToStartReindex {
            get {
                return ResourceManager.GetString("MessageFailedToStartReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindex status unknown.
        /// </summary>
        public static string MessageReindexStatusUnknown {
            get {
                return ResourceManager.GetString("MessageReindexStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SystemConfigurationSettingsProvider does not support user scoped settings..
        /// </summary>
        public static string SystemConfigurationSettingsProviderUserSetting {
            get {
                return ResourceManager.GetString("SystemConfigurationSettingsProviderUserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after study receipt/import.
        /// </summary>
        public static string TimeOriginReceivedDate {
            get {
                return ResourceManager.GetString("TimeOriginReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after study date/time.
        /// </summary>
        public static string TimeOriginStudyDate {
            get {
                return ResourceManager.GetString("TimeOriginStudyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        public static string TimeUnitDays {
            get {
                return ResourceManager.GetString("TimeUnitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour(s).
        /// </summary>
        public static string TimeUnitHours {
            get {
                return ResourceManager.GetString("TimeUnitHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s).
        /// </summary>
        public static string TimeUnitMinutes {
            get {
                return ResourceManager.GetString("TimeUnitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s).
        /// </summary>
        public static string TimeUnitWeeks {
            get {
                return ResourceManager.GetString("TimeUnitWeeks", resourceCulture);
            }
        }
    }
}
