//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Volume.Mpr.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MprSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MprSettings defaultInstance = ((MprSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MprSettings())));
        
        public static MprSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// How far apart MPR images should be spaced, as a multiple of the voxel diagonal of the source images.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("How far apart MPR images should be spaced, as a multiple of the voxel diagonal of" +
            " the source images.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float SliceSpacingFactor {
            get {
                return ((float)(this["SliceSpacingFactor"]));
            }
            set {
                this["SliceSpacingFactor"] = value;
            }
        }
        
        /// <summary>
        /// Specifies whether or not the spacing between MPR slices should be automatically determined based on the voxel size of the source images.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Specifies whether or not the spacing between MPR slices should be automatically d" +
            "etermined based on the voxel size of the source images.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSliceSpacing {
            get {
                return ((bool)(this["AutoSliceSpacing"]));
            }
            set {
                this["AutoSliceSpacing"] = value;
            }
        }
    }
}
