//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Client {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class HomePageSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HomePageSettings defaultInstance = ((HomePageSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HomePageSettings())));
        
        public static HomePageSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Indicates whether homepage will appear automatically when desktop application is started.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Indicates whether homepage will appear automatically when desktop application is " +
            "started.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHomepageOnStartUp {
            get {
                return ((bool)(this["ShowHomepageOnStartUp"]));
            }
            set {
                this["ShowHomepageOnStartUp"] = value;
            }
        }
        
        /// <summary>
        /// Indicates whether user is prevented from closing homepage.  Ignored if ShowHomepageOnStartUp is false.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Indicates whether user is prevented from closing homepage.  Ignored if ShowHomepa" +
            "geOnStartUp is false.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreventHomepageFromClosing {
            get {
                return ((bool)(this["PreventHomepageFromClosing"]));
            }
            set {
                this["PreventHomepageFromClosing"] = value;
            }
        }
    }
}
