//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Client {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class RandomUtilsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RandomUtilsSettings defaultInstance = ((RandomUtilsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RandomUtilsSettings())));
        
        public static RandomUtilsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Dictionary of male first names used in random order generation.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Dictionary of male first names used in random order generation.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dictionary.Name.Male.txt")]
        public string MaleNameDictionary {
            get {
                return ((string)(this["MaleNameDictionary"]));
            }
        }
        
        /// <summary>
        /// Dictionary of female first names used in random order generation.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Dictionary of female first names used in random order generation.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dictionary.Name.Female.txt")]
        public string FemaleNameDictionary {
            get {
                return ((string)(this["FemaleNameDictionary"]));
            }
        }
        
        /// <summary>
        /// Dictionary of surnames used in random order generation.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Dictionary of surnames used in random order generation.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dictionary.Name.Family.txt")]
        public string FamilyNameDictionary {
            get {
                return ((string)(this["FamilyNameDictionary"]));
            }
        }
    }
}
