//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Client {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class WorklistEditorComponentSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static WorklistEditorComponentSettings defaultInstance = ((WorklistEditorComponentSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WorklistEditorComponentSettings())));
        
        public static WorklistEditorComponentSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// User default value for worklist class
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("User default value for worklist class")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultWorklistClass {
            get {
                return ((string)(this["DefaultWorklistClass"]));
            }
            set {
                this["DefaultWorklistClass"] = value;
            }
        }
        
        /// <summary>
        /// User default value for worklist category
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("User default value for worklist category")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultWorklistCategory {
            get {
                return ((string)(this["DefaultWorklistCategory"]));
            }
            set {
                this["DefaultWorklistCategory"] = value;
            }
        }
        
        /// <summary>
        /// Indicates whether TranscribedBy page should be visible.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Indicates whether TranscribedBy page should be visible.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTranscribedByPage {
            get {
                return ((bool)(this["ShowTranscribedByPage"]));
            }
        }
    }
}
