//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Enterprise.Core.Modelling {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class EntityValidationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EntityValidationSettings defaultInstance = ((EntityValidationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EntityValidationSettings())));
        
        public static EntityValidationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Specifies the maximum amount of time that the server may cache custom server-side validation rules.  Changes to rules may not take affect until this period of time has elapsed.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Specifies the maximum amount of time that the server may cache custom server-side" +
            " validation rules.  Changes to rules may not take affect until this period of ti" +
            "me has elapsed.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int CustomRulesCachingTimeToLiveSeconds {
            get {
                return ((int)(this["CustomRulesCachingTimeToLiveSeconds"]));
            }
        }
    }
}
