//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InputValidation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between 1 and 100.
        /// </summary>
        internal static string AdminDevices_ThrottleSettings_InvalidNumOfConnections {
            get {
                return ResourceManager.GetString("AdminDevices_ThrottleSettings_InvalidNumOfConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be a positive integer.
        /// </summary>
        internal static string AdminPartitionArchive_InvalidDelay {
            get {
                return ResourceManager.GetString("AdminPartitionArchive_InvalidDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user group already exists..
        /// </summary>
        internal static string AdminUserGroups_UserGroupAlreadyExists {
            get {
                return ResourceManager.GetString("AdminUserGroups_UserGroupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a comment for the reason for deleting the series for future auditing purposes..
        /// </summary>
        internal static string DeleteSeriesConfirmDialog_MissingComment {
            get {
                return ResourceManager.GetString("DeleteSeriesConfirmDialog_MissingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a name for the reason..
        /// </summary>
        internal static string DeleteSeriesConfirmDialog_MissingName {
            get {
                return ResourceManager.GetString("DeleteSeriesConfirmDialog_MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the reason for deleting the series for future auditing purposes..
        /// </summary>
        internal static string DeleteSeriesConfirmDialog_MissingReason {
            get {
                return ResourceManager.GetString("DeleteSeriesConfirmDialog_MissingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a comment for the reason for deleting the studies for future auditing purposes..
        /// </summary>
        internal static string DeleteStudyConfirmDialog_MissingComment {
            get {
                return ResourceManager.GetString("DeleteStudyConfirmDialog_MissingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a name for the reason..
        /// </summary>
        internal static string DeleteStudyConfirmDialog_MissingName {
            get {
                return ResourceManager.GetString("DeleteStudyConfirmDialog_MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the reason for deleting the studies for future auditing purposes..
        /// </summary>
        internal static string DeleteStudyConfirmDialog_MissingReason {
            get {
                return ResourceManager.GetString("DeleteStudyConfirmDialog_MissingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AE Title already exists.
        /// </summary>
        internal static string DuplicateAETitle {
            get {
                return ResourceManager.GetString("DuplicateAETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Age must contain only digits and may not be negative.
        /// </summary>
        internal static string EditStudyDialog_InvalidPatientAge {
            get {
                return ResourceManager.GetString("EditStudyDialog_InvalidPatientAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a comment for the reason for editing the studies for future auditing purposes..
        /// </summary>
        internal static string EditStudyDialog_MissingComment {
            get {
                return ResourceManager.GetString("EditStudyDialog_MissingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a name for the reason..
        /// </summary>
        internal static string EditStudyDialog_MissingName {
            get {
                return ResourceManager.GetString("EditStudyDialog_MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the reason for editing the studies for future auditing purposes..
        /// </summary>
        internal static string EditStudyDialog_MissingReason {
            get {
                return ResourceManager.GetString("EditStudyDialog_MissingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalidly formatted..
        /// </summary>
        internal static string EmailAddressInvalid {
            get {
                return ResourceManager.GetString("EmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Watermark must be between 1 and 99 and less than the Low Watermark.
        /// </summary>
        internal static string HighWatermark_InvalidRange {
            get {
                return ResourceManager.GetString("HighWatermark_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AE Title.
        /// </summary>
        internal static string InvalidAETitle {
            get {
                return ResourceManager.GetString("InvalidAETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data Access Rule Condition.
        /// </summary>
        internal static string InvalidDataRule {
            get {
                return ResourceManager.GetString("InvalidDataRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition Folder Name is either invalid or is being used for another partition..
        /// </summary>
        internal static string InvalidPartitionFolderName {
            get {
                return ResourceManager.GetString("InvalidPartitionFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an invalid DICOM Patient ID..
        /// </summary>
        internal static string InvalidPatientID {
            get {
                return ResourceManager.GetString("InvalidPatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be between 1 and 65535.
        /// </summary>
        internal static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule must have a name.
        /// </summary>
        internal static string InvalidRuleName {
            get {
                return ResourceManager.GetString("InvalidRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time.
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Watermark must be between 1 and 99 and less than the High Watermark.
        /// </summary>
        internal static string LowWatermark_InvalidRange {
            get {
                return ResourceManager.GetString("LowWatermark_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Person Name. Each field may contain up to 64 characters..
        /// </summary>
        internal static string PersonNameInputPanel_InvalidName {
            get {
                return ResourceManager.GetString("PersonNameInputPanel_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for Patient&apos;s Sex.  If you choose to use data in these images, Patient&apos;s Sex of the study will be set to Other. Howerver, you can still edit the study after the reconciliation has completed..
        /// </summary>
        internal static string SIQ_ReconcileDialog_PatientSexOverriddenOnMerge {
            get {
                return ResourceManager.GetString("SIQ_ReconcileDialog_PatientSexOverriddenOnMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user id already exists.
        /// </summary>
        internal static string UserIDAlreadyExists {
            get {
                return ResourceManager.GetString("UserIDAlreadyExists", resourceCulture);
            }
        }
    }
}
