//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Layout.Basic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Layout.Basic.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explode Tile.
        /// </summary>
        public static string CommandExplodeTile {
            get {
                return ResourceManager.GetString("CommandExplodeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout image boxes.
        /// </summary>
        public static string CommandLayoutImageBoxes {
            get {
                return ResourceManager.GetString("CommandLayoutImageBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout tiles.
        /// </summary>
        public static string CommandLayoutTiles {
            get {
                return ResourceManager.GetString("CommandLayoutTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey/Explode.
        /// </summary>
        public static string CommandSurveyExplode {
            get {
                return ResourceManager.GetString("CommandSurveyExplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (List of Display Sets).
        /// </summary>
        public static string DisplaySets {
            get {
                return ResourceManager.GetString("DisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified image is not currently loaded (SopInstanceUID={0})..
        /// </summary>
        public static string ExceptionImageNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionImageNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified series is not currently loaded (SeriesInstanceUID={0})..
        /// </summary>
        public static string ExceptionSeriesNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionSeriesNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified study is not currently loaded (StudyInstanceUID={0})..
        /// </summary>
        public static string ExceptionStudyNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionStudyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in use.
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create single image display sets.
        /// </summary>
        public static string LabelCreateSingleImageDisplaySets {
            get {
                return ResourceManager.GetString("LabelCreateSingleImageDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default).
        /// </summary>
        public static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The study is {0}..
        /// </summary>
        public static string LabelFormatStudyUnavailable {
            get {
                return ResourceManager.GetString("LabelFormatStudyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Priors ....
        /// </summary>
        public static string LabelLoadingPriors {
            get {
                return ResourceManager.GetString("LabelLoadingPriors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split multi-echo series.
        /// </summary>
        public static string LabelSplitEchos {
            get {
                return ResourceManager.GetString("LabelSplitEchos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split mixed mult-frame series.
        /// </summary>
        public static string LabelSplitMultiframes {
            get {
                return ResourceManager.GetString("LabelSplitMultiframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The study could not be loaded..
        /// </summary>
        public static string LabelStudyCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("LabelStudyCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey/Explode.
        /// </summary>
        public static string MenuExplodeImageBox {
            get {
                return ResourceManager.GetString("MenuExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Manager.
        /// </summary>
        public static string MenuLayoutManager {
            get {
                return ResourceManager.GetString("MenuLayoutManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Display Set.
        /// </summary>
        public static string MenuNextDisplaySet {
            get {
                return ResourceManager.GetString("MenuNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Display Set.
        /// </summary>
        public static string MenuPreviousDisplaySet {
            get {
                return ResourceManager.GetString("MenuPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide &amp;Colour Bar.
        /// </summary>
        public static string MenuShowHideColorBar {
            get {
                return ResourceManager.GetString("MenuShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide DICOM Overlay(s).
        /// </summary>
        public static string MenuShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Scale Overlay.
        /// </summary>
        public static string MenuShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Shutter Overlay.
        /// </summary>
        public static string MenuShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Text Overlay.
        /// </summary>
        public static string MenuShowHideTextOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string MenuStandard {
            get {
                return ResourceManager.GetString("MenuStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred while loading prior studies:.
        /// </summary>
        public static string MessageLoadPriorsErrorPrefix {
            get {
                return ResourceManager.GetString("MessageLoadPriorsErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search for prior studies did not complete successfully because at least one of your default servers was unreachable.
        ///Although some priors may be available, please be aware that you may be working with an incomplete patient history.
        ///
        ///PLEASE NOTE that you will NOT be notified of this problem again for as long as this problem persists..
        /// </summary>
        public static string MessagePriorsIncomplete {
            get {
                return ResourceManager.GetString("MessagePriorsIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search for prior studies has failed.  Try reopening the study or select a different default server.
        ///
        ///PLEASE NOTE that you will NOT be notified of this problem again for as long as this problem persists..
        /// </summary>
        public static string MessageSearchForPriorsFailed {
            get {
                return ResourceManager.GetString("MessageSearchForPriorsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Bar.
        /// </summary>
        public static string NameColourBarOverlay {
            get {
                return ResourceManager.GetString("NameColourBarOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM.
        /// </summary>
        public static string NameDicomOverlay {
            get {
                return ResourceManager.GetString("NameDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string NameScaleOverlay {
            get {
                return ResourceManager.GetString("NameScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter.
        /// </summary>
        public static string NameShutterOverlay {
            get {
                return ResourceManager.GetString("NameShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string NameTextOverlay {
            get {
                return ResourceManager.GetString("NameTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearline.
        /// </summary>
        public static string Nearline {
            get {
                return ResourceManager.GetString("Nearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Sets.
        /// </summary>
        public static string TitleDisplaySetCreationConfiguration {
            get {
                return ResourceManager.GetString("TitleDisplaySetCreationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string TitleLayoutConfiguration {
            get {
                return ResourceManager.GetString("TitleLayoutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Manager.
        /// </summary>
        public static string TitleLayoutManager {
            get {
                return ResourceManager.GetString("TitleLayoutManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Layout.
        /// </summary>
        public static string ToolbarChangeLayout {
            get {
                return ResourceManager.GetString("ToolbarChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour Bar.
        /// </summary>
        public static string ToolbarColorBar {
            get {
                return ResourceManager.GetString("ToolbarColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Overlay(s).
        /// </summary>
        public static string ToolbarDicomOverlay {
            get {
                return ResourceManager.GetString("ToolbarDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey/Explode.
        /// </summary>
        public static string ToolbarExplodeImageBox {
            get {
                return ResourceManager.GetString("ToolbarExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Box Layout.
        /// </summary>
        public static string ToolbarLayoutBoxesChooser {
            get {
                return ResourceManager.GetString("ToolbarLayoutBoxesChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Layout.
        /// </summary>
        public static string ToolbarLayoutTilesChooser {
            get {
                return ResourceManager.GetString("ToolbarLayoutTilesChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Display Set.
        /// </summary>
        public static string ToolbarNextDisplaySet {
            get {
                return ResourceManager.GetString("ToolbarNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Display Set.
        /// </summary>
        public static string ToolbarPreviousDisplaySet {
            get {
                return ResourceManager.GetString("ToolbarPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Overlay.
        /// </summary>
        public static string ToolbarScaleOverlay {
            get {
                return ResourceManager.GetString("ToolbarScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Overlays.
        /// </summary>
        public static string ToolbarShowHideOverlays {
            get {
                return ResourceManager.GetString("ToolbarShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Overlay.
        /// </summary>
        public static string ToolbarShutterOverlay {
            get {
                return ResourceManager.GetString("ToolbarShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Overlay.
        /// </summary>
        public static string ToolbarTextOverlay {
            get {
                return ResourceManager.GetString("ToolbarTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Layout.
        /// </summary>
        public static string TooltipChangeLayout {
            get {
                return ResourceManager.GetString("TooltipChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey/Explode.
        /// </summary>
        public static string TooltipExplodeImageBox {
            get {
                return ResourceManager.GetString("TooltipExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all overlays.
        /// </summary>
        public static string TooltipHideOverlays {
            get {
                return ResourceManager.GetString("TooltipHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Display Set.
        /// </summary>
        public static string TooltipNextDisplaySet {
            get {
                return ResourceManager.GetString("TooltipNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Display Set.
        /// </summary>
        public static string TooltipPreviousDisplaySet {
            get {
                return ResourceManager.GetString("TooltipPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Overlay.
        /// </summary>
        public static string TooltipScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Colour Bar.
        /// </summary>
        public static string TooltipShowHideColorBar {
            get {
                return ResourceManager.GetString("TooltipShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide DICOM Overlay(s).
        /// </summary>
        public static string TooltipShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Overlays.
        /// </summary>
        public static string TooltipShowHideOverlays {
            get {
                return ResourceManager.GetString("TooltipShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Scale Overlay.
        /// </summary>
        public static string TooltipShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Shutter Overlay.
        /// </summary>
        public static string TooltipShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Text Overlay.
        /// </summary>
        public static string TooltipShowHideTextOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selected overlays.
        /// </summary>
        public static string TooltipShowOverlays {
            get {
                return ResourceManager.GetString("TooltipShowOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unavailable.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
    }
}
