#region License

// Copyright (c) 2013, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This file is part of the ClearCanvas RIS/PACS open source project.
//
// The ClearCanvas RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The ClearCanvas RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the ClearCanvas RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

// This file is auto-generated by the ClearCanvas.Model.SqlServer.CodeGenerator project.

namespace ClearCanvas.ImageServer.Model
{
    using System;
    using System.Collections.Generic;
    using ClearCanvas.ImageServer.Model.EntityBrokers;
    using ClearCanvas.ImageServer.Enterprise;
    using System.Reflection;

[Serializable]
public partial class QCStatusEnum : ServerEnum
{
      #region Private Static Members
      private static readonly QCStatusEnum _Processing = GetEnum("Processing");
      private static readonly QCStatusEnum _NA = GetEnum("NA");
      private static readonly QCStatusEnum _Passed = GetEnum("Passed");
      private static readonly QCStatusEnum _Failed = GetEnum("Failed");
      private static readonly QCStatusEnum _Incomplete = GetEnum("Incomplete");
      #endregion

      #region Public Static Properties
      /// <summary>
      /// Processing
      /// </summary>
      public static QCStatusEnum Processing
      {
          get { return _Processing; }
      }
      /// <summary>
      /// Not Applicable
      /// </summary>
      public static QCStatusEnum NA
      {
          get { return _NA; }
      }
      /// <summary>
      /// Passed
      /// </summary>
      public static QCStatusEnum Passed
      {
          get { return _Passed; }
      }
      /// <summary>
      /// Failed
      /// </summary>
      public static QCStatusEnum Failed
      {
          get { return _Failed; }
      }
      /// <summary>
      /// Incomplete (Missing required scans)
      /// </summary>
      public static QCStatusEnum Incomplete
      {
          get { return _Incomplete; }
      }

      #endregion

      #region Constructors
      public QCStatusEnum():base("QCStatusEnum")
      {}
      #endregion
      #region Public Members
      public override void SetEnum(short val)
      {
          ServerEnumHelper<QCStatusEnum, IQCStatusEnumBroker>.SetEnum(this, val);
      }
      static public List<QCStatusEnum> GetAll()
      {
          return ServerEnumHelper<QCStatusEnum, IQCStatusEnumBroker>.GetAll();
      }
      static public QCStatusEnum GetEnum(string lookup)
      {
          return ServerEnumHelper<QCStatusEnum, IQCStatusEnumBroker>.GetEnum(lookup);
      }
      #endregion
}
}
