//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Dicom.Network {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Dicom.Network.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message was not understood..
        /// </summary>
        internal static string CannotUnderstand {
            get {
                return ResourceManager.GetString("CannotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate SOP Instance could not be processed..
        /// </summary>
        internal static string DuplicateSOPInstance {
            get {
                return ResourceManager.GetString("DuplicateSOPInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some instances of this study are not supported by the remote application. See log for more details..
        /// </summary>
        internal static string ErrorSendSopClassNotSupported {
            get {
                return ResourceManager.GetString("ErrorSendSopClassNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected failure reported by the printer..
        /// </summary>
        internal static string MessagePrinterError {
            get {
                return ResourceManager.GetString("MessagePrinterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred due to a missing DICOM attribute..
        /// </summary>
        internal static string MissingAttribute {
            get {
                return ResourceManager.GetString("MissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote server is out of resources..
        /// </summary>
        internal static string OutOfResources {
            get {
                return ResourceManager.GetString("OutOfResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure occurred while processing..
        /// </summary>
        internal static string ProcessingFailure {
            get {
                return ResourceManager.GetString("ProcessingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve failed due to the remote application not being able to reach your computer, possibly due to misconfiguration..
        /// </summary>
        internal static string QueryRetrieveMoveDestinationUnknown {
            get {
                return ResourceManager.GetString("QueryRetrieveMoveDestinationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote server was unable to process the request..
        /// </summary>
        internal static string UnableToProcess {
            get {
                return ResourceManager.GetString("UnableToProcess", resourceCulture);
            }
        }
    }
}
