//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.StudyManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.StudyManagement.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ColumnActivityDescription {
            get {
                return ResourceManager.GetString("ColumnActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string ColumnPatient {
            get {
                return ResourceManager.GetString("ColumnPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string ColumnPriority {
            get {
                return ResourceManager.GetString("ColumnPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ColumnProgress {
            get {
                return ResourceManager.GetString("ColumnProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Time.
        /// </summary>
        public static string ColumnRequestedTime {
            get {
                return ResourceManager.GetString("ColumnRequestedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Time.
        /// </summary>
        public static string ColumnScheduledTime {
            get {
                return ResourceManager.GetString("ColumnScheduledTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Details.
        /// </summary>
        public static string ColumnStatusDescription {
            get {
                return ResourceManager.GetString("ColumnStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study.
        /// </summary>
        public static string ColumnStudy {
            get {
                return ResourceManager.GetString("ColumnStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk usage is above the maximum. The Workstation will not be able to import
        ///DICOM files or receive them over the network. You should delete old studies to
        ///make room, or increase the maximum usage..
        /// </summary>
        public static string DescriptionMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("DescriptionMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} ({2}%).
        /// </summary>
        public static string DiskspaceTemplate {
            get {
                return ResourceManager.GetString("DiskspaceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Activity Monitor.
        /// </summary>
        public static string LinkOpenActivityMonitor {
            get {
                return ResourceManager.GetString("LinkOpenActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Storage Configuration.
        /// </summary>
        public static string LinkOpenStorageConfiguration {
            get {
                return ResourceManager.GetString("LinkOpenStorageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Monitor.
        /// </summary>
        public static string MenuActivityMonitor {
            get {
                return ResourceManager.GetString("MenuActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuDeleteWorkItem {
            get {
                return ResourceManager.GetString("MenuDeleteWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-index File Store.
        /// </summary>
        public static string MenuReindex {
            get {
                return ResourceManager.GetString("MenuReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string MenuRestartWorkItem {
            get {
                return ResourceManager.GetString("MenuRestartWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Stat.
        /// </summary>
        public static string MenuStatWorkItem {
            get {
                return ResourceManager.GetString("MenuStatWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string MenuStopWorkItem {
            get {
                return ResourceManager.GetString("MenuStopWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling the selected work item(s) may result in partial study data, which could potentially lead to patient misdiagnosis.  Are you sure you want to cancel?.
        /// </summary>
        public static string MessageConfirmCancelWorkItems {
            get {
                return ResourceManager.GetString("MessageConfirmCancelWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the selected images..
        /// </summary>
        public static string MessageFailedToOpenImages {
            get {
                return ResourceManager.GetString("MessageFailedToOpenImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the selected studies..
        /// </summary>
        public static string MessageFailedToOpenStudy {
            get {
                return ResourceManager.GetString("MessageFailedToOpenStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start re-index..
        /// </summary>
        public static string MessageFailedToStartReindex {
            get {
                return ResourceManager.GetString("MessageFailedToStartReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently configured file store directory does not exist..
        /// </summary>
        public static string MessageFilestoreDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("MessageFilestoreDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the studies you selected are being processed. They may be incomplete or contain out-of-date information. Do you still want to continue?.
        /// </summary>
        public static string MessageLoadStudiesBeingProcessed {
            get {
                return ResourceManager.GetString("MessageLoadStudiesBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The study you selected is being processed. It may be incomplete or contain out-of-date information. Do you still want to continue?.
        /// </summary>
        public static string MessageLoadStudyBeingProcessed {
            get {
                return ResourceManager.GetString("MessageLoadStudyBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Local Server must be running in order to complete this operation..
        /// </summary>
        public static string MessageLocalServerNotRunning {
            get {
                return ResourceManager.GetString("MessageLocalServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum disk usage exceeded.
        /// </summary>
        public static string MessageMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("MessageMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed..
        /// </summary>
        public static string MessageNonStudyWorkItemFailed {
            get {
                return ResourceManager.GetString("MessageNonStudyWorkItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is 1 failed work item..
        /// </summary>
        public static string MessageOneFailedWorkItem {
            get {
                return ResourceManager.GetString("MessageOneFailedWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0} of {1} items....
        /// </summary>
        public static string MessageProcessedItemsProgress {
            get {
                return ResourceManager.GetString("MessageProcessedItemsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A re-index operation is already in progress..
        /// </summary>
        public static string MessageReindexInProgress {
            get {
                return ResourceManager.GetString("MessageReindexInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The re-index has been scheduled..
        /// </summary>
        public static string MessageReindexScheduled {
            get {
                return ResourceManager.GetString("MessageReindexScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service must be running to start a re-index..
        /// </summary>
        public static string MessageReindexServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageReindexServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} failed work items..
        /// </summary>
        public static string MessageTotalFailedWorkItems {
            get {
                return ResourceManager.GetString("MessageTotalFailedWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1} [{2}, A#:{3}] failed..
        /// </summary>
        public static string MessageWorkItemFailed {
            get {
                return ResourceManager.GetString("MessageWorkItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all).
        /// </summary>
        public static string NoFilterItem {
            get {
                return ResourceManager.GetString("NoFilterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string StatusFilterValueActive {
            get {
                return ResourceManager.GetString("StatusFilterValueActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string StatusFilterValueComplete {
            get {
                return ResourceManager.GetString("StatusFilterValueComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string StatusFilterValueFailed {
            get {
                return ResourceManager.GetString("StatusFilterValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string StatusFilterValueStopped {
            get {
                return ResourceManager.GetString("StatusFilterValueStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Monitor.
        /// </summary>
        public static string TitleActivityMonitor {
            get {
                return ResourceManager.GetString("TitleActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Monitor.
        /// </summary>
        public static string TooltipActivityMonitor {
            get {
                return ResourceManager.GetString("TooltipActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected work item(s).
        /// </summary>
        public static string TooltipDeleteWorkItem {
            get {
                return ResourceManager.GetString("TooltipDeleteWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart selected work item(s).
        /// </summary>
        public static string TooltipRestartWorkItem {
            get {
                return ResourceManager.GetString("TooltipRestartWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise priority of selected work item(s) to &apos;Stat&apos;.
        /// </summary>
        public static string TooltipStatWorkItem {
            get {
                return ResourceManager.GetString("TooltipStatWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop selected work item(s).
        /// </summary>
        public static string TooltipStopWorkItem {
            get {
                return ResourceManager.GetString("TooltipStopWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to open the Activity Monitor..
        /// </summary>
        public static string WarningActivityMonitorPermission {
            get {
                return ResourceManager.GetString("WarningActivityMonitorPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum disk usage has been exceeded.  Other devices will not be able to send studies to the workstation..
        /// </summary>
        public static string WarningMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("WarningMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to start a re-index..
        /// </summary>
        public static string WarningReindexPermission {
            get {
                return ResourceManager.GetString("WarningReindexPermission", resourceCulture);
            }
        }
    }
}
