//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageServer.Web.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageServer.Web.Common.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are images to be reconciled for this study.
        /// </summary>
        internal static string ActionNotAllowed_NeedReconcile {
            get {
                return ResourceManager.GetString("ActionNotAllowed_NeedReconcile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The study is stored on a research partition..
        /// </summary>
        internal static string ActionNotAllowed_ResearchPartition {
            get {
                return ResourceManager.GetString("ActionNotAllowed_ResearchPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some pending work queue item(s) for this study..
        /// </summary>
        internal static string ActionNotAllowed_StudyHasPendingWorkQueue {
            get {
                return ResourceManager.GetString("ActionNotAllowed_StudyHasPendingWorkQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This study is being archived.
        /// </summary>
        internal static string ActionNotAllowed_StudyIsBeingArchived {
            get {
                return ResourceManager.GetString("ActionNotAllowed_StudyIsBeingArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study is being processed..
        /// </summary>
        internal static string ActionNotAllowed_StudyIsBeingProcessing {
            get {
                return ResourceManager.GetString("ActionNotAllowed_StudyIsBeingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study has been locked..
        /// </summary>
        internal static string ActionNotAllowed_StudyIsLocked {
            get {
                return ResourceManager.GetString("ActionNotAllowed_StudyIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study has been archived as lossless but is currently in lossy compression state. It must be restored first..
        /// </summary>
        internal static string ActionNotAllowed_StudyIsLossyOnline {
            get {
                return ResourceManager.GetString("ActionNotAllowed_StudyIsLossyOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study is nearline..
        /// </summary>
        internal static string ActionNotAllowed_StudyIsNearline {
            get {
                return ResourceManager.GetString("ActionNotAllowed_StudyIsNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study has not been archived.
        /// </summary>
        internal static string ActionNotAllowed_StudyIsNotArchived {
            get {
                return ResourceManager.GetString("ActionNotAllowed_StudyIsNotArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study does not exist..
        /// </summary>
        internal static string ActionNotAllowed_StudyNotFound {
            get {
                return ResourceManager.GetString("ActionNotAllowed_StudyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current session is no longer valid..
        /// </summary>
        internal static string MessageCurrentSessionNoLongerValid {
            get {
                return ResourceManager.GetString("MessageCurrentSessionNoLongerValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASAP.
        /// </summary>
        internal static string Priority_Asap {
            get {
                return ResourceManager.GetString("Priority_Asap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback.
        /// </summary>
        internal static string Priority_Callback {
            get {
                return ResourceManager.GetString("Priority_Callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Op.
        /// </summary>
        internal static string Priority_PreOp {
            get {
                return ResourceManager.GetString("Priority_PreOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routine.
        /// </summary>
        internal static string Priority_Routine {
            get {
                return ResourceManager.GetString("Priority_Routine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat.
        /// </summary>
        internal static string Priority_Stat {
            get {
                return ResourceManager.GetString("Priority_Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing.
        /// </summary>
        internal static string Priority_Timing {
            get {
                return ResourceManager.GetString("Priority_Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web (@{0},{1} {2}, User:{3}).
        /// </summary>
        internal static string WebGUILogHeader {
            get {
                return ResourceManager.GetString("WebGUILogHeader", resourceCulture);
            }
        }
    }
}
