//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Shreds {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Shreds.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Server.
        /// </summary>
        internal static string DicomServer {
            get {
                return ResourceManager.GetString("DicomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shred hosts the DICOM Server and the WCF DICOM Server service.
        /// </summary>
        internal static string DicomServerDescription {
            get {
                return ResourceManager.GetString("DicomServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diskspace Manager.
        /// </summary>
        internal static string DiskspaceManager {
            get {
                return ResourceManager.GetString("DiskspaceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shred hosts the Diskspace Manager service.
        /// </summary>
        internal static string DiskspaceManagerDescription {
            get {
                return ResourceManager.GetString("DiskspaceManagerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process WorkItem Insert request..
        /// </summary>
        internal static string ExceptionErrorProcessingInsert {
            get {
                return ResourceManager.GetString("ExceptionErrorProcessingInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process WorkItem Publish request..
        /// </summary>
        internal static string ExceptionErrorProcessingPublish {
            get {
                return ResourceManager.GetString("ExceptionErrorProcessingPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process WorkItem Query request..
        /// </summary>
        internal static string ExceptionErrorProcessingQuery {
            get {
                return ResourceManager.GetString("ExceptionErrorProcessingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process WorkItem Refresh request..
        /// </summary>
        internal static string ExceptionErrorProcessingRefresh {
            get {
                return ResourceManager.GetString("ExceptionErrorProcessingRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process WorkItem Subscribe request..
        /// </summary>
        internal static string ExceptionErrorProcessingSubscribe {
            get {
                return ResourceManager.GetString("ExceptionErrorProcessingSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process WorkItem Unsubscribe request..
        /// </summary>
        internal static string ExceptionErrorProcessingUnsubscribe {
            get {
                return ResourceManager.GetString("ExceptionErrorProcessingUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process WorkItem Update request..
        /// </summary>
        internal static string ExceptionErrorProcessingUpdate {
            get {
                return ResourceManager.GetString("ExceptionErrorProcessingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restarting DICOM server..
        /// </summary>
        internal static string ExceptionErrorRestartingDICOMServer {
            get {
                return ResourceManager.GetString("ExceptionErrorRestartingDICOMServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files specified for import are no longer accessible..
        /// </summary>
        internal static string ExceptionInvalidFilesHaveBeenSpecifiedToImport {
            get {
                return ResourceManager.GetString("ExceptionInvalidFilesHaveBeenSpecifiedToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files have been specified to import..
        /// </summary>
        internal static string ExceptionNoFilesHaveBeenSpecifiedToImport {
            get {
                return ResourceManager.GetString("ExceptionNoFilesHaveBeenSpecifiedToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk usage exceeds maximum configured usage..
        /// </summary>
        internal static string ExceptionNotEnoughStorage {
            get {
                return ResourceManager.GetString("ExceptionNotEnoughStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process request. The service has been disabled..
        /// </summary>
        internal static string ExceptionServiceHasBeenDisabled {
            get {
                return ResourceManager.GetString("ExceptionServiceHasBeenDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filestore Management Processor.
        /// </summary>
        internal static string FilestoreManagementShred {
            get {
                return ResourceManager.GetString("FilestoreManagementShred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating: {0}.
        /// </summary>
        internal static string FormatEnumeratingFile {
            get {
                return ResourceManager.GetString("FormatEnumeratingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + {0}.
        /// </summary>
        internal static string FormatMultipleFilesDescription {
            get {
                return ResourceManager.GetString("FormatMultipleFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service has failed to start.  Please check the log for more details..
        /// </summary>
        internal static string FormatServiceFailedToStart {
            get {
                return ResourceManager.GetString("FormatServiceFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service has started successfully..
        /// </summary>
        internal static string FormatServiceStartedSuccessfully {
            get {
                return ResourceManager.GetString("FormatServiceStartedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service has stopped successfully..
        /// </summary>
        internal static string FormatServiceStoppedSuccessfully {
            get {
                return ResourceManager.GetString("FormatServiceStoppedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} WCF service has failed to start.  Please check the log for more details..
        /// </summary>
        internal static string FormatWCFServiceFailedToStart {
            get {
                return ResourceManager.GetString("FormatWCFServiceFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} WCF service has started successfully..
        /// </summary>
        internal static string FormatWCFServiceStartedSuccessfully {
            get {
                return ResourceManager.GetString("FormatWCFServiceStartedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} WCF service has stopped successfully..
        /// </summary>
        internal static string FormatWCFServiceStoppedSuccessfully {
            get {
                return ResourceManager.GetString("FormatWCFServiceStoppedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.  There may be incomplete imported studies, see the log file for details..
        /// </summary>
        internal static string ImportFailedPartialStudies {
            get {
                return ResourceManager.GetString("ImportFailedPartialStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error..
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.  No files could be found to import..
        /// </summary>
        internal static string MessageNoFilesToImport {
            get {
                return ResourceManager.GetString("MessageNoFilesToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.  No files could be found to reindex..
        /// </summary>
        internal static string MessageNoFilesToReindex {
            get {
                return ResourceManager.GetString("MessageNoFilesToReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Activity Monitor.
        /// </summary>
        internal static string WorkItemActivityMonitorService {
            get {
                return ResourceManager.GetString("WorkItemActivityMonitorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts the WorkItem Processor Service.
        /// </summary>
        internal static string WorkItemProcessorDescription {
            get {
                return ResourceManager.GetString("WorkItemProcessorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Processor.
        /// </summary>
        internal static string WorkItemProcessorService {
            get {
                return ResourceManager.GetString("WorkItemProcessorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item.
        /// </summary>
        internal static string WorkItemService {
            get {
                return ResourceManager.GetString("WorkItemService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts the WorkItem Services.
        /// </summary>
        internal static string WorkItemServiceDescription {
            get {
                return ResourceManager.GetString("WorkItemServiceDescription", resourceCulture);
            }
        }
    }
}
