//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Utilities.DicomEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Utilities.DicomEditor.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group-Element.
        /// </summary>
        internal static string ColumnHeadingGroupElement {
            get {
                return ResourceManager.GetString("ColumnHeadingGroupElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string ColumnHeadingLength {
            get {
                return ResourceManager.GetString("ColumnHeadingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Name.
        /// </summary>
        internal static string ColumnHeadingTagName {
            get {
                return ResourceManager.GetString("ColumnHeadingTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ColumnHeadingValue {
            get {
                return ResourceManager.GetString("ColumnHeadingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR.
        /// </summary>
        internal static string ColumnHeadingVR {
            get {
                return ResourceManager.GetString("ColumnHeadingVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient^Anonymous.
        /// </summary>
        internal static string DefaultAnonymousPatientName {
            get {
                return ResourceManager.GetString("DefaultAnonymousPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*).
        /// </summary>
        internal static string LabelAllFiles {
            get {
                return ResourceManager.GetString("LabelAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymize.
        /// </summary>
        internal static string MenuAnonymizeStudy {
            get {
                return ResourceManager.GetString("MenuAnonymizeStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string MenuCreate {
            get {
                return ResourceManager.GetString("MenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Dump.
        /// </summary>
        internal static string MenuDicomDump {
            get {
                return ResourceManager.GetString("MenuDicomDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Editor.
        /// </summary>
        internal static string MenuDicomEditor {
            get {
                return ResourceManager.GetString("MenuDicomEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string MenuNext {
            get {
                return ResourceManager.GetString("MenuNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string MenuPrevious {
            get {
                return ResourceManager.GetString("MenuPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick anonymize.
        /// </summary>
        internal static string MenuQuickAnonymize {
            get {
                return ResourceManager.GetString("MenuQuickAnonymize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate.
        /// </summary>
        internal static string MenuReplicate {
            get {
                return ResourceManager.GetString("MenuReplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        internal static string MenuRevert {
            get {
                return ResourceManager.GetString("MenuRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Accession Number must be between 0 and 16 characters..
        /// </summary>
        internal static string MessageAccessionNumberInvalidLength {
            get {
                return ResourceManager.GetString("MessageAccessionNumberInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to anonymize the study.  Please check the logs for more details..
        /// </summary>
        internal static string MessageAnonymizeStudyFailed {
            get {
                return ResourceManager.GetString("MessageAnonymizeStudyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymizing Study ....
        /// </summary>
        internal static string MessageAnonymizingStudy {
            get {
                return ResourceManager.GetString("MessageAnonymizingStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The study cannot be anonymized because the maximum disk usage has been exceeded..
        /// </summary>
        internal static string MessageCannotAnonymizeMaxDiskUsageExceeded {
            get {
                return ResourceManager.GetString("MessageCannotAnonymizeMaxDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to anonymize *all* loaded files in addition to this one?.
        /// </summary>
        internal static string MessageConfirmAnonymizeAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmAnonymizeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more files being anonymized are reports and/or other documents. These often contain patient information that cannot be completely cleaned by this tool. Are you sure you want to continue anonymization?.
        /// </summary>
        internal static string MessageConfirmAnonymizeOneOrMoreReportsAndAttachments {
            get {
                return ResourceManager.GetString("MessageConfirmAnonymizeOneOrMoreReportsAndAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file being anonymized is a report or other document. These often contain patient information that cannot be completely cleaned by this tool. Are you sure you want to continue anonymization?.
        /// </summary>
        internal static string MessageConfirmAnonymizeReportOrAttachment {
            get {
                return ResourceManager.GetString("MessageConfirmAnonymizeReportOrAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected tag(s) will be deleted.  Are you sure you want to continue?.
        /// </summary>
        internal static string MessageConfirmDeleteSelectedTags {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteSelectedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected tags from *all* the other loaded files in addition to the one selected?.
        /// </summary>
        internal static string MessageConfirmDeleteSelectedTagsFromAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteSelectedTagsFromAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports and other documents attached to a DICOM study often contain patient information that cannot be completely cleaned by this tool. Are you sure you want to keep these files?.
        /// </summary>
        internal static string MessageConfirmKeepReportsAndAttachments {
            get {
                return ResourceManager.GetString("MessageConfirmKeepReportsAndAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected tag(s) and their values will be replicated in *all* loaded files.  Are you sure you want to continue?
        ///
        ///NOTE: This will not automatically save the files. You must still click the Save tool to save the files..
        /// </summary>
        internal static string MessageConfirmReplicateTagsInAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmReplicateTagsInAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edits will be reverted to the last saved state.  Are you sure you want to continue?.
        /// </summary>
        internal static string MessageConfirmRevert {
            get {
                return ResourceManager.GetString("MessageConfirmRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to revert *all* loaded files in addition to this one?.
        /// </summary>
        internal static string MessageConfirmRevertAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmRevertAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will be saved to *all* loaded files and the original files will be overwritten.  Are you sure you want to continue?
        ///
        ///NOTE: If any of the edited files are open in the Study Filters, it should be closed. Otherwise, the edited values may appear unchanged..
        /// </summary>
        internal static string MessageConfirmSaveAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmSaveAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more files have been modified. Do you want to save the files now?.
        /// </summary>
        internal static string MessageConfirmSaveChangesBeforeClosing {
            get {
                return ResourceManager.GetString("MessageConfirmSaveChangesBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edited file is a report and/or other document. If you have modified any patient information, this tool cannot modify the document to match your changes. Are you sure you want to continue?.
        /// </summary>
        internal static string MessageConfirmSaveReportOrAttachment {
            get {
                return ResourceManager.GetString("MessageConfirmSaveReportOrAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the edited files are reports and/or other documents. If you have modified any patient information, this tool cannot modify the document to match your changes. Are you sure you want to continue?.
        /// </summary>
        internal static string MessageConfirmSaveReportsOrAttachments {
            get {
                return ResourceManager.GetString("MessageConfirmSaveReportsOrAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will be saved to the loaded file and the original file will be overwritten. Are you sure you want to continue?.
        /// </summary>
        internal static string MessageConfirmSaveSingleFile {
            get {
                return ResourceManager.GetString("MessageConfirmSaveSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will be saved to the loaded file and the original file will be overwritten. Are you sure you want to continue?.
        /// </summary>
        internal static string MessageConfirmSaveSingleRemoteFile {
            get {
                return ResourceManager.GetString("MessageConfirmSaveSingleRemoteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Files....
        /// </summary>
        internal static string MessageDumpProgressBar {
            get {
                return ResourceManager.GetString("MessageDumpProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving one or more of the selected files.  Please check the logs to make sure the indicated files are accessible and try again..
        /// </summary>
        internal static string MessageErrorUpdatingSomeFiles {
            get {
                return ResourceManager.GetString("MessageErrorUpdatingSomeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Dump operation failed.  File(s) in selection may not be DICOM..
        /// </summary>
        internal static string MessageFailedDump {
            get {
                return ResourceManager.GetString("MessageFailedDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid destination. You cannot save directly to the file store. Please save to another directory, then import the file(s) from that location..
        /// </summary>
        internal static string MessageFileStoreNotValidSaveLocation {
            get {
                return ResourceManager.GetString("MessageFileStoreNotValidSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Dump operation failed.  The selected path did not contain any files..
        /// </summary>
        internal static string MessageNoFilesSelected {
            get {
                return ResourceManager.GetString("MessageNoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags were deleted.  This is often because the selection only contains Sequence Items, Sequence Delimiter Items, and Item Delimiter Items which cannot be deleted..
        /// </summary>
        internal static string MessageNoTagsWereDeleted {
            get {
                return ResourceManager.GetString("MessageNoTagsWereDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected directory is not empty. Any existing files with conflicting filenames will be overwritten. Do you wish to continue?.
        /// </summary>
        internal static string MessageOutputFolderNotEmptyConfirmOverwriteFiles {
            get {
                return ResourceManager.GetString("MessageOutputFolderNotEmptyConfirmOverwriteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient Id cannot be empty..
        /// </summary>
        internal static string MessagePatientIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessagePatientIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient&apos;s name cannot be empty..
        /// </summary>
        internal static string MessagePatientsNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessagePatientsNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool is only valid when a DICOM Image is selected..
        /// </summary>
        internal static string MessagePleaseSelectAnImage {
            get {
                return ResourceManager.GetString("MessagePleaseSelectAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination folder..
        /// </summary>
        internal static string MessageSelectDestinationFolder {
            get {
                return ResourceManager.GetString("MessageSelectDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicating sequence and binary attributes is not supported..
        /// </summary>
        internal static string MessageSequenceBinaryReplicationNotSupported {
            get {
                return ResourceManager.GetString("MessageSequenceBinaryReplicationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag cannot be created.  Please ensure that the values are properly entered and are appropriate for the tag being created..
        /// </summary>
        internal static string MessageTagCannotBeCreated {
            get {
                return ResourceManager.GetString("MessageTagCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source data is not in a format the Dicom Editor can understand..
        /// </summary>
        internal static string MessageUnknownDataSource {
            get {
                return ResourceManager.GetString("MessageUnknownDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be empty..
        /// </summary>
        internal static string MessageValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessageValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value conflicts with the original value..
        /// </summary>
        internal static string MessageValueConflictsWithOriginal {
            get {
                return ResourceManager.GetString("MessageValueConflictsWithOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymize Study.
        /// </summary>
        internal static string TitleAnonymizeStudy {
            get {
                return ResourceManager.GetString("TitleAnonymizeStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tag.
        /// </summary>
        internal static string TitleCreateTag {
            get {
                return ResourceManager.GetString("TitleCreateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Dump.
        /// </summary>
        internal static string TitleDicomDump {
            get {
                return ResourceManager.GetString("TitleDicomDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Editor.
        /// </summary>
        internal static string TitleDicomEditor {
            get {
                return ResourceManager.GetString("TitleDicomEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Anonymize.
        /// </summary>
        internal static string TitleQuickAnonymize {
            get {
                return ResourceManager.GetString("TitleQuickAnonymize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string TitleSaveAs {
            get {
                return ResourceManager.GetString("TitleSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymize.
        /// </summary>
        internal static string ToolbarAnonymizeStudy {
            get {
                return ResourceManager.GetString("ToolbarAnonymizeStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string ToolbarCreate {
            get {
                return ResourceManager.GetString("ToolbarCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ToolbarDelete {
            get {
                return ResourceManager.GetString("ToolbarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ToolbarNext {
            get {
                return ResourceManager.GetString("ToolbarNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string ToolbarPrevious {
            get {
                return ResourceManager.GetString("ToolbarPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick anonymize.
        /// </summary>
        internal static string ToolbarQuickAnonymize {
            get {
                return ResourceManager.GetString("ToolbarQuickAnonymize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate.
        /// </summary>
        internal static string ToolbarReplicate {
            get {
                return ResourceManager.GetString("ToolbarReplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        internal static string ToolbarRevert {
            get {
                return ResourceManager.GetString("ToolbarRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ToolbarSave {
            get {
                return ResourceManager.GetString("ToolbarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string ToolbarSaveAs {
            get {
                return ResourceManager.GetString("ToolbarSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymize Selected Study.
        /// </summary>
        internal static string TooltipAnonymizeStudy {
            get {
                return ResourceManager.GetString("TooltipAnonymizeStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new tag.
        /// </summary>
        internal static string TooltipCreate {
            get {
                return ResourceManager.GetString("TooltipCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tag.
        /// </summary>
        internal static string TooltipDelete {
            get {
                return ResourceManager.GetString("TooltipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image.
        /// </summary>
        internal static string TooltipNext {
            get {
                return ResourceManager.GetString("TooltipNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous image.
        /// </summary>
        internal static string TooltipPrevious {
            get {
                return ResourceManager.GetString("TooltipPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymize all loaded files.
        /// </summary>
        internal static string TooltipQuickAnonymize {
            get {
                return ResourceManager.GetString("TooltipQuickAnonymize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicates selected tag to all loaded files.
        /// </summary>
        internal static string TooltipReplicate {
            get {
                return ResourceManager.GetString("TooltipReplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert changes.
        /// </summary>
        internal static string TooltipRevert {
            get {
                return ResourceManager.GetString("TooltipRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes, overwriting the original files.
        /// </summary>
        internal static string TooltipSave {
            get {
                return ResourceManager.GetString("TooltipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes as new files.
        /// </summary>
        internal static string TooltipSaveAs {
            get {
                return ResourceManager.GetString("TooltipSaveAs", resourceCulture);
            }
        }
    }
}
