//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.BaseTools {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MouseToolSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MouseToolSettings defaultInstance = ((MouseToolSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MouseToolSettings())));
        
        public static MouseToolSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// User preferences for mouse tools, such as mouse button assignments and whether or not to automatically select the tool when the viewer first opens.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("User preferences for mouse tools, such as mouse button assignments and whether or" +
            " not to automatically select the tool when the viewer first opens.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ClearCanvas.ImageViewer.BaseTools.MouseToolSettingsProfile DefaultProfile {
            get {
                return ((global::ClearCanvas.ImageViewer.BaseTools.MouseToolSettingsProfile)(this["DefaultProfile"]));
            }
            set {
                this["DefaultProfile"] = value;
            }
        }
        
        /// <summary>
        /// Specifies whether or not to show the mouse button assignment in the tool&apos;s icon.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Specifies whether or not to show the mouse button assignment in the tool\'s icon.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMouseButtonIconOverlay {
            get {
                return ((bool)(this["ShowMouseButtonIconOverlay"]));
            }
            set {
                this["ShowMouseButtonIconOverlay"] = value;
            }
        }
    }
}
