//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class ProductSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProductSettings defaultInstance = ((ProductSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProductSettings())));
        
        public static ProductSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// The product name.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The product name.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SXNTb0Nvb2xJc1MMeGV8dXlmXG1Lc0IA")]
        public string Component {
            get {
                return ((string)(this["Component"]));
            }
        }
        
        /// <summary>
        /// The version of the product, which can be different from that of the assemblies.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The version of the product, which can be different from that of the assemblies.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
        }
        
        /// <summary>
        /// Product version suffix (e.g. SP1).
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Product version suffix (e.g. SP1).")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IB82DjEsDgI=")]
        public string VersionSuffix {
            get {
                return ((string)(this["VersionSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SXNTb0Nvb2xJc1MMfUNdMVpTfkoiHCwA")]
        public string Product {
            get {
                return ((string)(this["Product"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Edition {
            get {
                return ((string)(this["Edition"]));
            }
        }
        
        /// <summary>
        /// Product copyright.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Product copyright.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SXBGd0NFaWpLMhIcHjkuXWZ3XGthfUJ2TWEBZUxiNy17XFMqUHRLZVN2Em5lcG9/TVVWLzUOHC8=")]
        public string Copyright {
            get {
                return ((string)(this["Copyright"]));
            }
        }
        
        /// <summary>
        /// Product license.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Product license.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SXBGd0NFaWpLMghPBio8LjshETlhcElhXlFAQlRgai1zXlwkLxdtYUslQHVna35+G0JXclB8akpBOD8XaHp1ahIvP3RReTNMRHhEfFNNbX9Jcj5tTBQEEgBLXmdCDGhrU3cARVwqfn94Zh12RDxYaEkyYkBHYGtOW15Ja1E9fkR0KmJdQ1AqYktVXCFGYWldRnMSbXJha39LdD4OLAMXe0B4BU1cSWJ7a2B+eExqLk1DTBlecG9dIlBiRUIPeWFreHFYOVJuQ2pJcVUMS3I5a0hVWipRckp5UGRAeTojc2JOEFFgWwMWXUByW250fGh4XXR1I096PU5GeQphQgxuZkxodncNcHo/f3FSa0MMempaMlRJXWd9PmV0HW1KeQxHYkcBa0dvfH9bXB9aV39AZEQIOFBpYG9jSFUSYEYubFpHeltuaGtlOkp5MHdOaz1pWnhALmNDZX1fYGJrDV9hamR7V3pYQ2AuH3dJWEdvfD58d09qS3NCIB8yTkoCdXFoNzpzY0F4Qn5CKRJzciMibE8QS25AfDxAVWJbcm4nIXtGeTBvR3p4XQhrQHxDRWxnBgwaAydNZnoqXFprUF5NY1FkQV8PWEdNJUJ8WnE8Q3BJfAFfTXRrbl8QT3hNd0luUyVbbyBnY35PQltjQHp5SwV/XD10ZmQ6QG9gZgZ6dU5cPUx6PSZ0YERtMGxIOXtsb3lDYh0MbHdLMndle0JBS14yfFd7PHtBfkBgYnZYIi1NWUtiTWhYLUJzV3Igd2JoG1lfcVlneUsFYVNvcm9vblEgf2UrBFBqel5tT354QkthTVladDlhbSpZf1p/aV1RH1Rvfg9LLk5LQGlQYUlgQX4ycXlwUVZefx4fKnF4SS1TbVc8R01fLXxVXGRHb3AiL0ZHf2xnYjpkaXNmSH14D05yVy5dQ3FsCGV1ekxwYmwkEjwDO3Vhdx9hSENaZmo+YnNLfAJuSWNJe1dJRiF4LVlfT3MCckotU21XPEdNXy18VVxkR29wD3VjUHFpbSFWQWN1bVVrPU5EcktpEFtqfUAMGnpFfC5cZnpXfHJNYHReYQB+ZlkhTktRbjlNbEluDGFOWVBifC1KQlBgR35YIwcle3ogbWV5FxBBZFAudFtRZggyL3l2bQZnfnYIYW9IB3FMbVVCcGxbLj4OLRkOHw==")]
        public string License {
            get {
                return ((string)(this["License"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IFtTeFRAYXJSd05YLwoOHg==")]
        public string Release {
            get {
                return ((string)(this["Release"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FamilyName {
            get {
                return ((string)(this["FamilyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubComponent {
            get {
                return ((string)(this["SubComponent"]));
            }
        }
    }
}
