//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Common.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve application root class {0} - multiple matches..
        /// </summary>
        public static string ExceptionApplicationRootMultipleMatches {
            get {
                return ResourceManager.GetString("ExceptionApplicationRootMultipleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve application root class {0} - no matches..
        /// </summary>
        public static string ExceptionApplicationRootNoMatches {
            get {
                return ResourceManager.GetString("ExceptionApplicationRootNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be non-negative..
        /// </summary>
        public static string ExceptionArgumentNegative {
            get {
                return ResourceManager.GetString("ExceptionArgumentNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero..
        /// </summary>
        public static string ExceptionArgumentNotPositive {
            get {
                return ResourceManager.GetString("ExceptionArgumentNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} = {0} is invalid. {3} must be &gt;= {1} and &lt;= {2}..
        /// </summary>
        public static string ExceptionArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background task is already running.
        /// </summary>
        public static string ExceptionBackgroundTaskAlreadyRunning {
            get {
                return ResourceManager.GetString("ExceptionBackgroundTaskAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must evaluate to Array, ICollection, or IEnumerable type..
        /// </summary>
        public static string ExceptionCastExpressionArrayCollectionEnumerable {
            get {
                return ResourceManager.GetString("ExceptionCastExpressionArrayCollectionEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must evaluate to Boolean type..
        /// </summary>
        public static string ExceptionCastExpressionBoolean {
            get {
                return ResourceManager.GetString("ExceptionCastExpressionBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must evaluate to IEnumerable type..
        /// </summary>
        public static string ExceptionCastExpressionEnumerable {
            get {
                return ResourceManager.GetString("ExceptionCastExpressionEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must evaluate to String type..
        /// </summary>
        public static string ExceptionCastExpressionString {
            get {
                return ResourceManager.GetString("ExceptionCastExpressionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition is not met :{0}.
        /// </summary>
        public static string ExceptionConditionIsNotMet {
            get {
                return ResourceManager.GetString("ExceptionConditionIsNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate plugin {0} found..
        /// </summary>
        public static string ExceptionDuplicatePluginFound {
            get {
                return ResourceManager.GetString("ExceptionDuplicatePluginFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        public static string ExceptionEmptyString {
            get {
                return ResourceManager.GetString("ExceptionEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type {0}..
        /// </summary>
        public static string ExceptionExpectedType {
            get {
                return ResourceManager.GetString("ExceptionExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension class {0} does not extend a valid extension point class..
        /// </summary>
        public static string ExceptionExtensionDoesNotExtendValidExtensionPointClass {
            get {
                return ResourceManager.GetString("ExceptionExtensionDoesNotExtendValidExtensionPointClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension class {0} does not implement required interface {1}..
        /// </summary>
        public static string ExceptionExtensionDoesNotImplementRequiredInterface {
            get {
                return ResourceManager.GetString("ExceptionExtensionDoesNotImplementRequiredInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension class {0} must be a concrete class..
        /// </summary>
        public static string ExceptionExtensionMustBeConcreteClass {
            get {
                return ResourceManager.GetString("ExceptionExtensionMustBeConcreteClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension point {0} is invalid because it is not a direct subclass of ExtensionPoint&lt;&gt;.
        /// </summary>
        public static string ExceptionExtensionPointMustSubclassExtensionPoint {
            get {
                return ResourceManager.GetString("ExceptionExtensionPointMustSubclassExtensionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to transfer file from {0} to {1}..
        /// </summary>
        public static string ExceptionFailedToTransferFile {
            get {
                return ResourceManager.GetString("ExceptionFailedToTransferFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, but an error has occurred that ClearCanvas Workstation cannot recover from.  Please check the log and restart..
        /// </summary>
        public static string ExceptionFatalApplicationError {
            get {
                return ResourceManager.GetString("ExceptionFatalApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert from String to {0}.
        /// </summary>
        public static string ExceptionFormatCannotConvertFromStringToType {
            get {
                return ResourceManager.GetString("ExceptionFormatCannotConvertFromStringToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert from {0} to String.
        /// </summary>
        public static string ExceptionFormatCannotConvertFromTypeToString {
            get {
                return ResourceManager.GetString("ExceptionFormatCannotConvertFromTypeToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization failed for object type &apos;{0}&apos;.
        /// </summary>
        public static string ExceptionFormatDeserializationFailedForType {
            get {
                return ResourceManager.GetString("ExceptionFormatDeserializationFailedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization failed for object type &apos;{0}&apos;.
        /// </summary>
        public static string ExceptionFormatSerializationFailedForType {
            get {
                return ResourceManager.GetString("ExceptionFormatSerializationFailedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}[{0}] is invalid.  Index must be &gt;= {1} and &lt;= {2}..
        /// </summary>
        public static string ExceptionIndexOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be of type {1}..
        /// </summary>
        public static string ExceptionInvalidCast {
            get {
                return ResourceManager.GetString("ExceptionInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid specification id..
        /// </summary>
        public static string ExceptionInvalidSpecificationId {
            get {
                return ResourceManager.GetString("ExceptionInvalidSpecificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JScript evaluation error on {0}: {1}.
        /// </summary>
        public static string ExceptionJScriptEvaluation {
            get {
                return ResourceManager.GetString("ExceptionJScriptEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has not been set.  Object state is invalid..
        /// </summary>
        public static string ExceptionMemberNotSet {
            get {
                return ResourceManager.GetString("ExceptionMemberNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has not been set.  {1}.
        /// </summary>
        public static string ExceptionMemberNotSetVerbose {
            get {
                return ResourceManager.GetString("ExceptionMemberNotSetVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one model plugin found..
        /// </summary>
        public static string ExceptionMoreThanOneModelPluginFound {
            get {
                return ResourceManager.GetString("ExceptionMoreThanOneModelPluginFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extensions found for extension point {0}, or the extensions could not be instantiated.  Please see the log for more information..
        /// </summary>
        public static string ExceptionNoExtensionsCreated {
            get {
                return ResourceManager.GetString("ExceptionNoExtensionsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins could be found..
        /// </summary>
        public static string ExceptionNoPluginsFound {
            get {
                return ResourceManager.GetString("ExceptionNoPluginsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins have been loaded..
        /// </summary>
        public static string ExceptionNoPluginsLoaded {
            get {
                return ResourceManager.GetString("ExceptionNoPluginsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly {0} is not a plugin..
        /// </summary>
        public static string ExceptionNotAPlugin {
            get {
                return ResourceManager.GetString("ExceptionNotAPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        public static string ExceptionPathDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} could not be found.  Unable to start plugin..
        /// </summary>
        public static string ExceptionPluginCouldNotBeFound {
            get {
                return ResourceManager.GetString("ExceptionPluginCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin directory could not be found..
        /// </summary>
        public static string ExceptionPluginDirectoryNotFound {
            get {
                return ResourceManager.GetString("ExceptionPluginDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading one or more plugins. Please see the log for more information..
        /// </summary>
        public static string ExceptionPluginWarning {
            get {
                return ResourceManager.GetString("ExceptionPluginWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0}  not found..
        /// </summary>
        public static string ExceptionResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No script engine available for language {0}..
        /// </summary>
        public static string ExceptionScriptEngineLanguage {
            get {
                return ResourceManager.GetString("ExceptionScriptEngineLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template evaluation generated an exception..
        /// </summary>
        public static string ExceptionTemplateEvaluation {
            get {
                return ResourceManager.GetString("ExceptionTemplateEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread pool has already been started..
        /// </summary>
        public static string ExceptionThreadPoolAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionThreadPoolAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread pool must be stopped before setting the {0} parameter..
        /// </summary>
        public static string ExceptionThreadPoolMustBeStopped {
            get {
                return ResourceManager.GetString("ExceptionThreadPoolMustBeStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread pool has not been started.  Unable to enqueue the specified item..
        /// </summary>
        public static string ExceptionThreadPoolNotStarted {
            get {
                return ResourceManager.GetString("ExceptionThreadPoolNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown.
        /// </summary>
        public static string ExceptionThrown {
            get {
                return ResourceManager.GetString("ExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load any plugins.  Please see the log for more information..
        /// </summary>
        public static string ExceptionUnableToLoadPlugins {
            get {
                return ResourceManager.GetString("ExceptionUnableToLoadPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bytes.
        /// </summary>
        public static string FormatFileSizeBytes {
            get {
                return ResourceManager.GetString("FormatFileSizeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f2} GB.
        /// </summary>
        public static string FormatFileSizeGB {
            get {
                return ResourceManager.GetString("FormatFileSizeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f2} KB.
        /// </summary>
        public static string FormatFileSizeKB {
            get {
                return ResourceManager.GetString("FormatFileSizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f2} MB.
        /// </summary>
        public static string FormatFileSizeMB {
            get {
                return ResourceManager.GetString("FormatFileSizeMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f2} TB.
        /// </summary>
        public static string FormatFileSizeTB {
            get {
                return ResourceManager.GetString("FormatFileSizeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded plugin: {0}.
        /// </summary>
        public static string FormatLoadedPlugin {
            get {
                return ResourceManager.GetString("FormatLoadedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing plugin: {0}.
        /// </summary>
        public static string FormatProcessingPlugin {
            get {
                return ResourceManager.GetString("FormatProcessingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        public static string FormatReleaseType {
            get {
                return ResourceManager.GetString("FormatReleaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string FormatSeconds {
            get {
                return ResourceManager.GetString("FormatSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be an interface..
        /// </summary>
        public static string FormatTypeMustBeInterface {
            get {
                return ResourceManager.GetString("FormatTypeMustBeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must implement interface &apos;{1}&apos;..
        /// </summary>
        public static string FormatTypeMustImplementInterface {
            get {
                return ResourceManager.GetString("FormatTypeMustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find matching action for &apos;{0}&apos; node in script.  Unable to perform action..
        /// </summary>
        public static string FormatUnableToFindMatchingAction {
            get {
                return ResourceManager.GetString("FormatUnableToFindMatchingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration store not found - defaulting to LocalFileSettingsProvider.
        /// </summary>
        public static string LogConfigurationStoreNotFound {
            get {
                return ResourceManager.GetString("LogConfigurationStoreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process plugin assembly {0} with the following exception(s):.
        /// </summary>
        public static string LogFailedToProcessPluginAssembly {
            get {
                return ResourceManager.GetString("LogFailedToProcessPluginAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unmanaged DLL: {0}.
        /// </summary>
        public static string LogFoundUnmanagedDLL {
            get {
                return ResourceManager.GetString("LogFoundUnmanagedDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License provider not found - defaulting to local license provider..
        /// </summary>
        public static string LogLicenseProviderNotFound {
            get {
                return ResourceManager.GetString("LogLicenseProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local configuration store not found - defaulting to LocalFileSettingsProvider.
        /// </summary>
        public static string LogLocalConfigurationStoreNotFound {
            get {
                return ResourceManager.GetString("LogLocalConfigurationStoreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded plugin: {0}.
        /// </summary>
        public static string LogPluginLoaded {
            get {
                return ResourceManager.GetString("LogPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time provider not found - defaulting to local machine time..
        /// </summary>
        public static string LogTimeProviderNotFound {
            get {
                return ResourceManager.GetString("LogTimeProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An extension point cannot extend IExtensionPoint..
        /// </summary>
        public static string MessageCannotExtendIExtensionPoint {
            get {
                return ResourceManager.GetString("MessageCannotExtendIExtensionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding plugins....
        /// </summary>
        public static string MessageFindingPlugins {
            get {
                return ResourceManager.GetString("MessageFindingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings scope not defined..
        /// </summary>
        public static string MessageSettingsScopeNotDefined {
            get {
                return ResourceManager.GetString("MessageSettingsScopeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} shred has failed to start.  Please check the log for more details..
        /// </summary>
        public static string ShredFailedToStart {
            get {
                return ResourceManager.GetString("ShredFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} shred has failed to stop.  Please check the log for more details..
        /// </summary>
        public static string ShredFailedToStop {
            get {
                return ResourceManager.GetString("ShredFailedToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} shred has started successfully..
        /// </summary>
        public static string ShredStartedSuccessfully {
            get {
                return ResourceManager.GetString("ShredStartedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0} Shred.
        /// </summary>
        public static string ShredStarting {
            get {
                return ResourceManager.GetString("ShredStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} shred has stopped successfully..
        /// </summary>
        public static string ShredStoppedSuccessfully {
            get {
                return ResourceManager.GetString("ShredStoppedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping {0} Shred.
        /// </summary>
        public static string ShredStopping {
            get {
                return ResourceManager.GetString("ShredStopping", resourceCulture);
            }
        }
    }
}
