//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Utilities.StudyFilters.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Utilities.StudyFilters.Tools.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch &amp;Edit.
        /// </summary>
        internal static string MenuBatchEdit {
            get {
                return ResourceManager.GetString("MenuBatchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filter Study.
        /// </summary>
        internal static string MenuFilterStudy {
            get {
                return ResourceManager.GetString("MenuFilterStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import to Local File Store.
        /// </summary>
        internal static string MenuImportToLocalDataStore {
            get {
                return ResourceManager.GetString("MenuImportToLocalDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Study &amp;Filters....
        /// </summary>
        internal static string MenuOpenInStudyFilters {
            get {
                return ResourceManager.GetString("MenuOpenInStudyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string MessageLoading {
            get {
                return ResourceManager.GetString("MessageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Filters.
        /// </summary>
        internal static string TitleStudyFilters {
            get {
                return ResourceManager.GetString("TitleStudyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Edit.
        /// </summary>
        internal static string ToolbarBatchEdit {
            get {
                return ResourceManager.GetString("ToolbarBatchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Study.
        /// </summary>
        internal static string ToolbarFilterStudy {
            get {
                return ResourceManager.GetString("ToolbarFilterStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import to Local File Store.
        /// </summary>
        internal static string ToolbarImportToLocalDataStore {
            get {
                return ResourceManager.GetString("ToolbarImportToLocalDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Study Filters.
        /// </summary>
        internal static string ToolbarOpenInStudyFilters {
            get {
                return ResourceManager.GetString("ToolbarOpenInStudyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the selected instances to the DICOM Editor for batch editing.
        /// </summary>
        internal static string TooltipBatchEdit {
            get {
                return ResourceManager.GetString("TooltipBatchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Study.
        /// </summary>
        internal static string TooltipFilterStudy {
            get {
                return ResourceManager.GetString("TooltipFilterStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports the selected instances to the Local File Store.
        /// </summary>
        internal static string TooltipImportToLocalDataStore {
            get {
                return ResourceManager.GetString("TooltipImportToLocalDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the selected DICOM files in a table for filtering purposes.
        /// </summary>
        internal static string TooltipOpenInStudyFilters {
            get {
                return ResourceManager.GetString("TooltipOpenInStudyFilters", resourceCulture);
            }
        }
    }
}
