//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.AdvancedImaging.Fusion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.AdvancedImaging.Fusion.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FoR MISMATCH.
        /// </summary>
        internal static string CodeMismatchedFrameOfReference {
            get {
                return ResourceManager.GetString("CodeMismatchedFrameOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdjustOpacity.
        /// </summary>
        internal static string CommandAdjustOpacity {
            get {
                return ResourceManager.GetString("CommandAdjustOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion: {0}/{1} ({2}).
        /// </summary>
        internal static string FormatPETFusionDisplaySet {
            get {
                return ResourceManager.GetString("FormatPETFusionDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - {0}.
        /// </summary>
        internal static string FormatReason {
            get {
                return ResourceManager.GetString("FormatReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Imaging (Fusion).
        /// </summary>
        internal static string LabelAdvancedImageFusion {
            get {
                return ResourceManager.GetString("LabelAdvancedImageFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenuation Correction.
        /// </summary>
        internal static string LabelAttenuationCorrection {
            get {
                return ResourceManager.GetString("LabelAttenuationCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion.
        /// </summary>
        internal static string LabelFusion {
            get {
                return ResourceManager.GetString("LabelFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched Frame of Reference.
        /// </summary>
        internal static string LabelMismatchedFrameOfReference {
            get {
                return ResourceManager.GetString("LabelMismatchedFrameOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Attenuation Correction.
        /// </summary>
        internal static string LabelNoAttentuationCorrection {
            get {
                return ResourceManager.GetString("LabelNoAttentuationCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust &amp;Opacity.
        /// </summary>
        internal static string MenuAdjustOpacity {
            get {
                return ResourceManager.GetString("MenuAdjustOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Debug.
        /// </summary>
        internal static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fusion.
        /// </summary>
        internal static string MenuFusion {
            get {
                return ResourceManager.GetString("MenuFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string MenuStandard {
            get {
                return ResourceManager.GetString("MenuStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion Complete.
        /// </summary>
        internal static string MessageFusionComplete {
            get {
                return ResourceManager.GetString("MessageFusionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fuse images.
        /// </summary>
        internal static string MessageFusionError {
            get {
                return ResourceManager.GetString("MessageFusionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusing Images....
        /// </summary>
        internal static string MessageFusionInProgress {
            get {
                return ResourceManager.GetString("MessageFusionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images have inconsistent frames of reference.
        /// </summary>
        internal static string MessageInconsistentFramesOfReference {
            get {
                return ResourceManager.GetString("MessageInconsistentFramesOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images have inconsistent orientation information.
        /// </summary>
        internal static string MessageInconsistentImageOrientation {
            get {
                return ResourceManager.GetString("MessageInconsistentImageOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images have inconsistent slice spacing.
        /// </summary>
        internal static string MessageInconsistentImageSpacing {
            get {
                return ResourceManager.GetString("MessageInconsistentImageSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images have inconsistent pixel spacing information.
        /// </summary>
        internal static string MessageInconsistentPixelSpacing {
            get {
                return ResourceManager.GetString("MessageInconsistentPixelSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid series.
        /// </summary>
        internal static string MessageInvalidSeries {
            get {
                return ResourceManager.GetString("MessageInvalidSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images lack orientation information.
        /// </summary>
        internal static string MessageMissingImageOrientation {
            get {
                return ResourceManager.GetString("MessageMissingImageOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images lack pixel spacing information.
        /// </summary>
        internal static string MessageMissingPixelSpacing {
            get {
                return ResourceManager.GetString("MessageMissingPixelSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images have an unsupported gantry tilt.
        /// </summary>
        internal static string MessageUnsupportedGantryTilt {
            get {
                return ResourceManager.GetString("MessageUnsupportedGantryTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion.
        /// </summary>
        internal static string TitleFusion {
            get {
                return ResourceManager.GetString("TitleFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Opacity.
        /// </summary>
        internal static string ToolbarAdjustOpacity {
            get {
                return ResourceManager.GetString("ToolbarAdjustOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion.
        /// </summary>
        internal static string ToolbarFusion {
            get {
                return ResourceManager.GetString("ToolbarFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string ToolbarStandard {
            get {
                return ResourceManager.GetString("ToolbarStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Opacity.
        /// </summary>
        internal static string TooltipAdjustOpacity {
            get {
                return ResourceManager.GetString("TooltipAdjustOpacity", resourceCulture);
            }
        }
    }
}
