//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Client.Workflow {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class PriorReportComponentSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PriorReportComponentSettings defaultInstance = ((PriorReportComponentSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PriorReportComponentSettings())));
        
        public static PriorReportComponentSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Indicates if the prior reports component should be restricted to relevant reports only by default.  Setting to false will display all reports by default.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Indicates if the prior reports component should be restricted to relevant reports" +
            " only by default.  Setting to false will display all reports by default.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRelevantPriorsOnly {
            get {
                return ((bool)(this["ShowRelevantPriorsOnly"]));
            }
            set {
                this["ShowRelevantPriorsOnly"] = value;
            }
        }
    }
}
