//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Client.Workflow.Extended {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ProtocollingSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProtocollingSettings defaultInstance = ((ProtocollingSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProtocollingSettings())));
        
        public static ProtocollingSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Stores user default protocol groups.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Stores user default protocol groups.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" ?><procedure-protocolgroup-defaults></proced" +
            "ure-protocolgroup-defaults>")]
        public string DefaultProtocolGroupsXml {
            get {
                return ((string)(this["DefaultProtocolGroupsXml"]));
            }
            set {
                this["DefaultProtocolGroupsXml"] = value;
            }
        }
        
        /// <summary>
        /// Stores user default supervisor.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Stores user default supervisor.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SupervisorID {
            get {
                return ((string)(this["SupervisorID"]));
            }
            set {
                this["SupervisorID"] = value;
            }
        }
        
        /// <summary>
        /// Indicates if a default supervisor should be automatically loaded if it is not yet specified.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Indicates if a default supervisor should be automatically loaded if it is not yet" +
            " specified.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldApplyDefaultSupervisor {
            get {
                return ((bool)(this["ShouldApplyDefaultSupervisor"]));
            }
            set {
                this["ShouldApplyDefaultSupervisor"] = value;
            }
        }
        
        /// <summary>
        /// Indicates whether the application allows multiple protocolling workspaces to be open at the same time.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Indicates whether the application allows multiple protocolling workspaces to be o" +
            "pen at the same time.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowMultipleProtocollingWorkspaces {
            get {
                return ((bool)(this["AllowMultipleProtocollingWorkspaces"]));
            }
        }
        
        /// <summary>
        /// Specifies the name of the initially selected tab.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Specifies the name of the initially selected tab.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Order Attachments")]
        public string InitiallySelectedTabPageName {
            get {
                return ((string)(this["InitiallySelectedTabPageName"]));
            }
            set {
                this["InitiallySelectedTabPageName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRAD")]
        public string SupervisorStaffTypeFilters {
            get {
                return ((string)(this["SupervisorStaffTypeFilters"]));
            }
        }
        
        /// <summary>
        /// The number of items to keep in the &quot;Next Item&quot; queue.  A higher value means fewer trips to the server, but also the possibility that higher priority items will not be seen by the user as quickly.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The number of items to keep in the \"Next Item\" queue.  A higher value means fewer" +
            " trips to the server, but also the possibility that higher priority items will n" +
            "ot be seen by the user as quickly.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int NextItemQueueCacheSize {
            get {
                return ((int)(this["NextItemQueueCacheSize"]));
            }
        }
    }
}
