//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Dicom {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class DicomSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DicomSettings defaultInstance = ((DicomSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DicomSettings())));
        
        public static DicomSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// When set, the lengths of DICOM tags will be validated.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("When set, the lengths of DICOM tags will be validated.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ValidateVrLengths {
            get {
                return ((bool)(this["ValidateVrLengths"]));
            }
        }
        
        /// <summary>
        /// When set, the values of DICOM Attributes will be checked.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("When set, the values of DICOM Attributes will be checked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ValidateVrValues {
            get {
                return ((bool)(this["ValidateVrValues"]));
            }
        }
        
        /// <summary>
        /// When set, tags that are out of range will be ignored.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("When set, tags that are out of range will be ignored.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreOutOfRangeTags {
            get {
                return ((bool)(this["IgnoreOutOfRangeTags"]));
            }
        }
    }
}
